[build]
functions = "netlify/functions"
publish = "."
command = "echo 'Build completed'"

[functions]
node_bundler = "esbuild"

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[build.environment]
NODE_VERSION = "18"
